/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author SPECTRE
 */
public class CustomerFrequent extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrequent
     */
    public CustomerFrequent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        puntosL = new javax.swing.JLabel();
        puntosUsuarioL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Programa Cliente Frecuente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        puntosL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        puntosL.setText("Putntos");
        jPanel1.add(puntosL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        puntosUsuarioL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        puntosUsuarioL.setText("jLabel3");
        jPanel1.add(puntosUsuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel puntosL;
    private javax.swing.JLabel puntosUsuarioL;
    // End of variables declaration//GEN-END:variables
}
