/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarJoin;
import DAO.UsuarioDAO;
import Entidad.Usuario;
//import static Frontera.FramePrincipal.sistema;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author nicro
 */
public class Join extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Join() {
        initComponents();
        this.setTitle("Airline Tickets Application");
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono avion.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        nombreTF = new javax.swing.JTextField();
        apellidoTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        verificarPasswordTF = new javax.swing.JPasswordField();
        aviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(550, 600));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aceptar.setBackground(new java.awt.Color(0, 0, 0));
        aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptarRegistro.png"))); // NOI18N
        aceptar.setText("Registrar");
        aceptar.setContentAreaFilled(false);
        aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        panelPrincipal.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 160, 40));

        regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptarRegistro.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.setContentAreaFilled(false);
        regresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        panelPrincipal.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 160, 30));
        panelPrincipal.add(nombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, -1));
        panelPrincipal.add(apellidoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, -1));
        panelPrincipal.add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 210, -1));
        panelPrincipal.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 190, -1));
        panelPrincipal.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 190, -1));
        panelPrincipal.add(verificarPasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 160, -1));

        aviso.setBackground(new java.awt.Color(255, 0, 0));
        aviso.setForeground(new java.awt.Color(255, 0, 0));
        aviso.setEnabled(false);
        panelPrincipal.add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 260, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Formulario.png"))); // NOI18N
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        UsuarioDAO udao = new UsuarioDAO();

        String nombre = nombreTF.getText(), apellido = apellidoTF.getText(), email = emailTF.getText(),
        username = usernameTF.getText(), password = passwordTF.getText();

        usuario.setNombre(nombre);
        usuario.setApellido(apellido);
        usuario.setEmail(email);
        usuario.setUsername(username);
        usuario.setPassword(password);
        String verificarPassword = verificarPasswordTF.getText();

        ValidarJoin verificar = new ValidarJoin();

        String respuesta = verificar.verificarJoin(usuario, verificarPassword);
        aviso.setForeground(Color.red);
        
        if(respuesta.equals("Longitud de nombre incorrecta")) 
            aviso.setText("Longitud de nombre incorrecta");
        
        else if(respuesta.equals("Longitud de apellido incorrecta")) 
            aviso.setText("Longitud de apellido incorrecta");
        
        else if(respuesta.equals("Longitud de email incorrecto"))
            aviso.setText("Longitud de email incorrecto");

        else if(respuesta.equals("Email inválido"))
            aviso.setText("Email inválido");

        else if(respuesta.equals("Longitud de username incorrecta"))
            aviso.setText("Longitud de username incorrecta");

        else if(respuesta.equals("El primer caracter del username no puede ser un número"))
            aviso.setText("El primer caracter del username no puede ser un número");

        else if(respuesta.equals("El username ya existe"))
            aviso.setText("El username ya existe");

        else if(respuesta.equals("El email ya existe"))
            aviso.setText("El email ya está registrado");
        
        else if(respuesta.equals("Longitud de contraseña incorrecta"))
            aviso.setText("Longitud de contraseña incorrecta");
         
        else if(respuesta.equals("Las contraseñas no coinciden"))
            aviso.setText("Las contraseñas no coinciden");
        
        else {
            //sistema.addUsuarios(usuario);
            System.out.println("-------");
            System.out.println("NUEVO USUARIO AÑADIDO");
            System.out.println("Nombre: " + nombre);
            System.out.println("Apellido: " + apellido);
            System.out.println("Email: " + email);
            System.out.println("Username: " + username);
        }

        System.out.println("-------");
        System.out.println(respuesta);
    }//GEN-LAST:event_aceptarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        FramePrincipal framePrincipal = new FramePrincipal();
        this.setVisible(false);
        framePrincipal.setLocationRelativeTo(this);
        framePrincipal.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apellidoTF;
    private javax.swing.JLabel aviso;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JPasswordField verificarPasswordTF;
    // End of variables declaration//GEN-END:variables
}
