/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.Reserva;
import static Frontera.Login.user;
import javax.swing.ImageIcon;

/**
 *
 * @author lucas
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form menuInicial
     */
    public MenuInicial() {
        initComponents();
        this.setTitle("Airline Tickets Application");
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono avion.png")).getImage());
        
        if(!user.getUsername().equals("admin")) {
            estadisticasB.setVisible(false);
            this.setSize(500, 350);
        }
        
        else {
            this.setSize(635, 350);
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
            jPanel1.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));
            jPanel1.add(terminarSesionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        reserva = new javax.swing.JButton();
        terminarSesionB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pagoReservacionB = new javax.swing.JButton();
        clienteFrecuenteB = new javax.swing.JButton();
        estadisticasB = new javax.swing.JButton();

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("Iniciar sesión");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        bienvenido.setText("BIENVENIDO");
        jPanel1.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 35));

        reserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnReservarP.png"))); // NOI18N
        reserva.setText("Reservar");
        reserva.setContentAreaFilled(false);
        reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reserva.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnReservarP.png"))); // NOI18N
        reserva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnReservarG.png"))); // NOI18N
        reserva.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        reserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservaMouseClicked(evt);
            }
        });
        reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaActionPerformed(evt);
            }
        });
        jPanel1.add(reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 107));

        terminarSesionB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        terminarSesionB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPlane.png"))); // NOI18N
        terminarSesionB.setText("Terminar Sesión");
        terminarSesionB.setContentAreaFilled(false);
        terminarSesionB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        terminarSesionB.setInheritsPopupMenu(true);
        terminarSesionB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPlane.png"))); // NOI18N
        terminarSesionB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBack.png"))); // NOI18N
        terminarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarSesionBActionPerformed(evt);
            }
        });
        jPanel1.add(terminarSesionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono avion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pagoReservacionB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagoReservacionB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPagoTarjetaP.png"))); // NOI18N
        pagoReservacionB.setContentAreaFilled(false);
        pagoReservacionB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagoReservacionB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pagoReservacionB.setLabel("Pago Reservación");
        pagoReservacionB.setMaximumSize(new java.awt.Dimension(97, 93));
        pagoReservacionB.setMinimumSize(new java.awt.Dimension(97, 93));
        pagoReservacionB.setPreferredSize(new java.awt.Dimension(97, 93));
        pagoReservacionB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPagoTarjetaP.png"))); // NOI18N
        pagoReservacionB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPagoTarjetaG.png"))); // NOI18N
        pagoReservacionB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pagoReservacionB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pagoReservacionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoReservacionBActionPerformed(evt);
            }
        });
        jPanel1.add(pagoReservacionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 107));

        clienteFrecuenteB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clienteFrecuenteB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnClienteFrecuenteP.png"))); // NOI18N
        clienteFrecuenteB.setText("Cliente Frecuente");
        clienteFrecuenteB.setContentAreaFilled(false);
        clienteFrecuenteB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clienteFrecuenteB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clienteFrecuenteB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnClienteFrecuenteP.png"))); // NOI18N
        clienteFrecuenteB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnClienteFrecuenteG.png"))); // NOI18N
        clienteFrecuenteB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        clienteFrecuenteB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clienteFrecuenteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteFrecuenteBActionPerformed(evt);
            }
        });
        jPanel1.add(clienteFrecuenteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 160, 107));

        estadisticasB.setText("Estadísticas");
        estadisticasB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estadisticasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasBActionPerformed(evt);
            }
        });
        jPanel1.add(estadisticasB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaActionPerformed
       ReservationIda reservation = new ReservationIda();
       reservation.setLocationRelativeTo(this);
       this.setVisible(false);
       reservation.setVisible(true);
    }//GEN-LAST:event_reservaActionPerformed

    private void reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reservaMouseClicked

    private void terminarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarSesionBActionPerformed
        // TODO add your handling code here:
        user = null;
        FramePrincipal framePrincipal = new FramePrincipal();
        framePrincipal.setLocationRelativeTo(this);
        this.setVisible(false);
        framePrincipal.setVisible(true);
    }//GEN-LAST:event_terminarSesionBActionPerformed

    private void pagoReservacionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoReservacionBActionPerformed
        // TODO add your handling code here:
        ReservationPayment ticketPayment = new ReservationPayment();
        ticketPayment.setLocationRelativeTo(this);
        this.setVisible(false);
        ticketPayment.setVisible(true);
    }//GEN-LAST:event_pagoReservacionBActionPerformed

    private void clienteFrecuenteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteFrecuenteBActionPerformed
        // TODO add your handling code here:
        CustomerFrequent clienteFrecuente = new CustomerFrequent();
        clienteFrecuente.setLocationRelativeTo(this);
        this.setVisible(false);
        clienteFrecuente.setVisible(true);
        //clienteFrecuente.setAlwaysOnTop(true);
    }//GEN-LAST:event_clienteFrecuenteBActionPerformed

    private void estadisticasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasBActionPerformed
        // TODO add your handling code here:
        Statistics estadisticas = new Statistics();
        estadisticas.setLocationRelativeTo(this);
        this.setVisible(false);
        estadisticas.setVisible(true);
    }//GEN-LAST:event_estadisticasBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton clienteFrecuenteB;
    private javax.swing.JButton estadisticasB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pagoReservacionB;
    private javax.swing.JButton reserva;
    private javax.swing.JButton terminarSesionB;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
