/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarPagoTarjeta;
import DAO.CreditCardDAO;
import DAO.ReservaDAO;
import DAO.TicketDAO;
import Entidad.CreditCard;
import Entidad.Reserva;
import Entidad.Ticket;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author nicro
 */
public class ReservationPayment extends javax.swing.JFrame {
    boolean reservaActived;
    Reserva reserva;
    ReservaDAO rdao;
    List<Reserva> listReserva;
    
    /**
     * Creates new form TicketPayment
     */
    public ReservationPayment() {
        initComponents();
        this.setTitle("Airline Tickets Application");
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono avion.png")).getImage());
        
        reserva = null;
        rdao = new ReservaDAO();
        listReserva = rdao.leeralltolist();
        reservaActived = false;
        informacionTarjetaL.setVisible(false);
        nombreBancoL.setVisible(false);
        nombreBancoCB.setVisible(false);
        fechaCaducidadL.setVisible(false);
        mesCaducidadTF.setVisible(false);
        nombreTitularL.setVisible(false);
        nombreTitularTF.setVisible(false);
        numeroTarjetaL.setVisible(false);
        numeroTarjetaTF.setVisible(false);
        mesCaducidadTF.setVisible(false);
        añoCaducidadTF.setVisible(false);
        numeroTarjetaTF.setVisible(false);
        añoL.setVisible(false);
        mesL.setVisible(false);
        numeroSeguridadL.setVisible(false);
        numeroSeguridadTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idReservacionL = new javax.swing.JLabel();
        idReservacionTF = new javax.swing.JTextField();
        avisoL = new javax.swing.JLabel();
        informacionTarjetaL = new javax.swing.JLabel();
        nombreBancoL = new javax.swing.JLabel();
        fechaCaducidadL = new javax.swing.JLabel();
        aceptarConfirmarB = new javax.swing.JButton();
        nombreTitularL = new javax.swing.JLabel();
        numeroTarjetaL = new javax.swing.JLabel();
        volverCambiarDeReservaB = new javax.swing.JButton();
        mesCaducidadTF = new javax.swing.JTextField();
        nombreTitularTF = new javax.swing.JTextField();
        numeroTarjetaTF = new javax.swing.JTextField();
        mesL = new javax.swing.JLabel();
        añoL = new javax.swing.JLabel();
        añoCaducidadTF = new javax.swing.JTextField();
        numeroSeguridadL = new javax.swing.JLabel();
        numeroSeguridadTF = new javax.swing.JTextField();
        nombreBancoCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pago de Reservación");

        idReservacionL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idReservacionL.setText("ID reservación");

        idReservacionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservacionTFActionPerformed(evt);
            }
        });
        idReservacionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idReservacionTFKeyTyped(evt);
            }
        });

        avisoL.setForeground(java.awt.Color.red);

        informacionTarjetaL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        informacionTarjetaL.setText("Informacion Tarjeta de Crédito");

        nombreBancoL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBancoL.setText("Nombre del banco");

        fechaCaducidadL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaCaducidadL.setText("Fecha de caducidad");

        aceptarConfirmarB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aceptarConfirmarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPlane.png"))); // NOI18N
        aceptarConfirmarB.setText("Siguiente");
        aceptarConfirmarB.setContentAreaFilled(false);
        aceptarConfirmarB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPlane.png"))); // NOI18N
        aceptarConfirmarB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnNext.png"))); // NOI18N
        aceptarConfirmarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarConfirmarBActionPerformed(evt);
            }
        });

        nombreTitularL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreTitularL.setText("Nombre del titular");

        numeroTarjetaL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroTarjetaL.setText("Número de la tarjeta");

        volverCambiarDeReservaB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volverCambiarDeReservaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPlane.png"))); // NOI18N
        volverCambiarDeReservaB.setText("Cancelar");
        volverCambiarDeReservaB.setContentAreaFilled(false);
        volverCambiarDeReservaB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPlane.png"))); // NOI18N
        volverCambiarDeReservaB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBack.png"))); // NOI18N
        volverCambiarDeReservaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverCambiarDeReservaBActionPerformed(evt);
            }
        });

        mesL.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        mesL.setText("Mes");

        añoL.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        añoL.setText("Año");

        numeroSeguridadL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroSeguridadL.setText("Número de Seguridad");

        nombreBancoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bancolombia", "AV Villas", "Davivienda", "Banco Popular" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(idReservacionL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(idReservacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(avisoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(127, 127, 127))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreTitularL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numeroTarjetaL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroTarjetaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(informacionTarjetaL)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nombreBancoL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombreTitularTF)
                                            .addComponent(nombreBancoCB, 0, 179, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(volverCambiarDeReservaB)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(numeroSeguridadL)
                                        .addGap(75, 75, 75)
                                        .addComponent(numeroSeguridadTF))
                                    .addComponent(fechaCaducidadL)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(226, 226, 226)
                                        .addComponent(mesL)
                                        .addGap(18, 18, 18)
                                        .addComponent(mesCaducidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(añoL)
                                .addGap(3, 3, 3)
                                .addComponent(añoCaducidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aceptarConfirmarB)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idReservacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idReservacionL))
                .addGap(32, 32, 32)
                .addComponent(informacionTarjetaL)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreBancoL)
                    .addComponent(nombreBancoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTitularL)
                    .addComponent(nombreTitularTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroTarjetaL)
                    .addComponent(numeroTarjetaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesL)
                    .addComponent(mesCaducidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoCaducidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaCaducidadL)
                    .addComponent(añoL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroSeguridadL)
                    .addComponent(numeroSeguridadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverCambiarDeReservaB)
                    .addComponent(aceptarConfirmarB))
                .addGap(62, 62, 62)
                .addComponent(avisoL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverCambiarDeReservaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverCambiarDeReservaBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuInicial menu = new MenuInicial();
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
        menu.setAlwaysOnTop(true);
    }//GEN-LAST:event_volverCambiarDeReservaBActionPerformed

    private void aceptarConfirmarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarConfirmarBActionPerformed
         ValidarPagoTarjeta validar = new ValidarPagoTarjeta();
        String id = idReservacionTF.getText();
        
        if(!reservaActived) {
            if(id.length() != 0) {
                if(validar.verificarReserva(Integer.parseInt(id))) {
                    informacionTarjetaL.setVisible(true);
                    nombreBancoL.setVisible(true);
                    nombreBancoCB.setVisible(true);
                    fechaCaducidadL.setVisible(true);
                    añoCaducidadTF.setVisible(true);
                    mesCaducidadTF.setVisible(true);
                    mesL.setVisible(true);
                    añoL.setVisible(true);
                    nombreTitularL.setVisible(true);
                    nombreTitularTF.setVisible(true);
                    numeroTarjetaL.setVisible(true);
                    numeroTarjetaTF.setVisible(true);
                    numeroSeguridadL.setVisible(true);
                    numeroSeguridadTF.setVisible(true);
                    avisoL.setText("");
                    idReservacionTF.setEnabled(false);
                    aceptarConfirmarB.setText("Confirmar");
                    volverCambiarDeReservaB.setText("Cambiar reserva");
                    reservaActived = true;
                
                    for(int i = 0; i < listReserva.size(); i++) {
                        if(listReserva.get(i).getId() == Integer.parseInt(id))
                            reserva = listReserva.get(i);
                    }    
                }
        
                else {
                avisoL.setText("La reserva no existe");
                }
            }
        
            else {
                avisoL.setText("Ingrese una reservación");
            }
        }
        
        else {
            String nombreBanco = (String)nombreBancoCB.getSelectedItem(), mesCaducidad = mesCaducidadTF.getText(), añoCaducidad = añoCaducidadTF.getText(), nombreTitular = nombreTitularTF.getText(), 
                     numeroTarjeta = numeroTarjetaTF.getText(), numeroSeguridad = numeroSeguridadTF.getText() ;
            
            CreditCard tarjetaIngresada = new CreditCard(nombreBanco, mesCaducidad, añoCaducidad, nombreTitular, numeroTarjeta, numeroSeguridad);
            CreditCardDAO tdao = new CreditCardDAO();
            List<CreditCard> lista = tdao.leeralltolist();
            CreditCard tarjetaAntigua = null;
            String resultado = null;
            
          /*for(int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getNombreBanco().equals(nombreBanco) && lista.get(i).getFechaCaducidad().equals(fechaCaducidad) && lista.get(i).getMarcaInternacional().equals(marcaInternacional)
                        && lista.get(i).getNombreTitular().equals(nombreTitular) && lista.get(i).getNumeroTarjeta().equals(numeroTarjeta)) {
                        
                    tarjetaAntigua = lista.get(i);
                }
            }*/
            String query = "t.nombreBanco LIKE '"+nombreBanco+
                    "' AND t.nombreTitular LIKE '"+nombreTitular+
                    "' AND t.numeroTarjeta LIKE '"+numeroTarjeta+"'";
            if(tdao.leerquerycount(query) == 1){
                for(CreditCard t : tdao.leerquerytolist(query)){
                    tarjetaAntigua = t;
                }
                resultado = validar.verificarPagoTarjeta(Integer.parseInt(id), tarjetaAntigua, reserva.getPrecio());
            } else if(tdao.leerquerycount(query) == 0) {
                resultado = validar.verificarPagoTarjeta(Integer.parseInt(id), tarjetaIngresada, reserva.getPrecio());
            } else {
                resultado = validar.verificarPagoTarjeta(Integer.parseInt(id), tarjetaAntigua, reserva.getPrecio());
            }
            
            if(resultado.equals("Longitud del nombre del banco incorrecta")) 
                avisoL.setText("Longitud del nombre del banco incorrecta");
            
            else if(resultado.equals("Fecha de expiración incorrecta")) 
                avisoL.setText("Fecha de expiración incorrecta");
            
            else if(resultado.equals("Longitud del nombre del titular incorrecta")) 
                avisoL.setText("Longitud del nombre del titular incorrecta");
            
            else if(resultado.equals("Longitud de marca internacional incorrecta")) 
                avisoL.setText("Longitud de marca internacional incorrecta");
            
            else if(resultado.equals("Longitud del numero de la tarjeta incorrecta")) 
                avisoL.setText("Longitud del numero de la tarjeta incorrecta");
            
            else if(resultado.equals("La tarjeta de crédito no se encuentra registrada"))
                avisoL.setText("La tarjeta de crédito no se encuentra registrada");
            
            else if(resultado.equals("No hay cupo suficiente en la tarjeta para realizar el pago")) 
                avisoL.setText("No hay cupo suficiente en la tarjeta para realizar el pago");
                
            else {
                //CreditCard tarjetaNueva = tarjetaAntigua;
                double cupoGastado = tarjetaAntigua.getCupoGastado() + reserva.getPrecio();
                //tarjetaNueva.setCupoGastado(cupoGastado + reserva.getPrecio());
                
                tdao.actualizarcupo(tarjetaAntigua, cupoGastado);
                
                TicketDAO tckdao = new TicketDAO();
                Ticket ticketPagado = new Ticket(reserva);
                
                tckdao.crear(ticketPagado);
                
                this.setVisible(false);
                MenuInicial menu = new MenuInicial();
                menu.setVisible(true);
                menu.setLocationRelativeTo(this);
                menu.setVisible(true);
                menu.setAlwaysOnTop(true);
            }
            //if(tarjetaAntigua.equals(null))
            if(tdao.leerquerycount(query) == 0)
            
            System.out.println("-------");
            System.out.println(resultado);
        }
    
    }//GEN-LAST:event_aceptarConfirmarBActionPerformed

    private void idReservacionTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idReservacionTFKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(c < '0' || c > '9') //Sólo se puede escribir números
        evt.consume();
    }//GEN-LAST:event_idReservacionTFKeyTyped

    private void idReservacionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservacionTFActionPerformed
        // TODO add your handling code here:
        ValidarPagoTarjeta validar = new ValidarPagoTarjeta();

        String id = idReservacionTF.getText();

        if(id.length() != 0) {
            if(validar.verificarReserva(Integer.parseInt(id))) {
                informacionTarjetaL.setVisible(true);
                nombreBancoL.setVisible(true);
                nombreBancoCB.setVisible(true);
                fechaCaducidadL.setVisible(true);
                mesCaducidadTF.setVisible(true);
                nombreTitularL.setVisible(true);
                nombreTitularTF.setVisible(true);
                numeroTarjetaL.setVisible(true);
                numeroTarjetaTF.setVisible(true);
                añoL.setVisible(true);
                mesL.setVisible(true);
                numeroSeguridadTF.setVisible(true);
                numeroSeguridadL.setVisible(true);
                
                avisoL.setText("");
                idReservacionTF.setEnabled(false);
                aceptarConfirmarB.setText("Confirmar");
                volverCambiarDeReservaB.setText("Cambiar reserva");
                reservaActived = true;

                for(int i = 0; i < listReserva.size(); i++) {
                    if(listReserva.get(i).getId() == Integer.parseInt(id))
                    reserva = listReserva.get(i);
                }
            }

            else {
                avisoL.setText("La reserva no existe");
            }
        }

        else {
            avisoL.setText("Ingrese una reservación");
        }
    }//GEN-LAST:event_idReservacionTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarConfirmarB;
    private javax.swing.JLabel avisoL;
    private javax.swing.JTextField añoCaducidadTF;
    private javax.swing.JLabel añoL;
    private javax.swing.JLabel fechaCaducidadL;
    private javax.swing.JLabel idReservacionL;
    private javax.swing.JTextField idReservacionTF;
    private javax.swing.JLabel informacionTarjetaL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mesCaducidadTF;
    private javax.swing.JLabel mesL;
    private javax.swing.JComboBox<String> nombreBancoCB;
    private javax.swing.JLabel nombreBancoL;
    private javax.swing.JLabel nombreTitularL;
    private javax.swing.JTextField nombreTitularTF;
    private javax.swing.JLabel numeroSeguridadL;
    private javax.swing.JTextField numeroSeguridadTF;
    private javax.swing.JLabel numeroTarjetaL;
    private javax.swing.JTextField numeroTarjetaTF;
    private javax.swing.JButton volverCambiarDeReservaB;
    // End of variables declaration//GEN-END:variables
}
