/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author nicro
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        OrigenCB = new javax.swing.JComboBox<>();
        origen = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        destinoCB = new javax.swing.JComboBox<>();
        hora = new javax.swing.JLabel();
        horaCB = new javax.swing.JComboBox<>();
        idaVuelta = new javax.swing.JLabel();
        idaVueltaCB = new javax.swing.JCheckBox();
        noPuestos = new javax.swing.JLabel();
        noPuestosCB = new javax.swing.JComboBox<>();
        categoria = new javax.swing.JLabel();
        categoriaCB = new javax.swing.JComboBox<>();
        equipaje = new javax.swing.JLabel();
        equipajeCB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("Realizar reservación");

        OrigenCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Item 2", "Item 3", "Item 4" }));

        origen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        origen.setText("Origen");

        destino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destino.setText("Destino");

        destinoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Item 2", "Item 3", "Item 4" }));

        hora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hora.setText("Hora");

        horaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Item 2", "Item 3", "Item 4" }));

        idaVuelta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idaVuelta.setText("Ida y vuelta");

        idaVueltaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idaVueltaCBActionPerformed(evt);
            }
        });

        noPuestos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noPuestos.setText("No. puestos");

        noPuestosCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "1", "2", "3", "4" }));

        categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoria.setText("Categoría");

        categoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turista", "Ejecutiva", "Primera clase" }));

        equipaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipaje.setText("Equipaje");

        equipajeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipajeCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(titulo))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(origen)
                            .addGap(36, 36, 36)
                            .addComponent(OrigenCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(destino)
                            .addGap(46, 46, 46)
                            .addComponent(destinoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(hora)
                            .addGap(47, 47, 47)
                            .addComponent(horaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(noPuestos)
                            .addGap(18, 18, 18)
                            .addComponent(noPuestosCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(categoria)
                            .addGap(18, 18, 18)
                            .addComponent(categoriaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(idaVuelta)
                            .addGap(6, 6, 6)
                            .addComponent(idaVueltaCB)
                            .addGap(51, 51, 51)
                            .addComponent(equipaje)
                            .addGap(6, 6, 6)
                            .addComponent(equipajeCB)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulo)
                    .addGap(33, 33, 33)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(origen)
                        .addComponent(OrigenCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(destino)
                        .addComponent(destinoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hora)
                        .addComponent(horaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noPuestos)
                        .addComponent(noPuestosCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(categoria)
                        .addComponent(categoriaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idaVuelta)
                        .addComponent(idaVueltaCB)
                        .addComponent(equipaje)
                        .addComponent(equipajeCB))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idaVueltaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idaVueltaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idaVueltaCBActionPerformed

    private void equipajeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipajeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipajeCBActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> OrigenCB;
    private javax.swing.JLabel categoria;
    private javax.swing.JComboBox<String> categoriaCB;
    private javax.swing.JLabel destino;
    private javax.swing.JComboBox<String> destinoCB;
    private javax.swing.JLabel equipaje;
    private javax.swing.JCheckBox equipajeCB;
    private javax.swing.JLabel hora;
    private javax.swing.JComboBox<String> horaCB;
    private javax.swing.JLabel idaVuelta;
    private javax.swing.JCheckBox idaVueltaCB;
    private javax.swing.JLabel noPuestos;
    private javax.swing.JComboBox<String> noPuestosCB;
    private javax.swing.JLabel origen;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
