/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.CalcularPrecio;
import DAO.ReservaDAO;
import Entidad.Reserva;
import Entidad.Vuelo;
import static Frontera.Login.user;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author lucas
 */
public class ReservationResumen extends javax.swing.JFrame {
    private double precioSubtotal, precioImpuestos, precioTotal;
    //public static int idReserva = 0;
    private int numeroReserva;
    
    private Reserva reserva;
    
    private String origen, destino, fechaSalida, horaSalida, categoria, peso1;
    private boolean isIdaVuelta, isEquipaje;
    int puestosReservados, peso;
    private Vuelo vueloIda;
    
    private String categoriaVuelta, peso1Vuelta;
    private boolean isEquipajeVuelta;
    int puestosReservadosVuelta, pesoVuelta;
    private Vuelo vueloVuelta1;
   
    public ReservationResumen(/*int numeroReserva,*/ Vuelo vueloIda, int puestosReservados, String categoria, boolean isEquipaje, int peso, String peso1, boolean isIdaVuelta) {
        //this.numeroReserva = numeroReserva;
        this.vueloIda = vueloIda;
        this.origen = vueloIda.getOrigen();
        this.puestosReservados = puestosReservados;
        this.destino = vueloIda.getDestino();
        this.fechaSalida = vueloIda.getFecha();
        this.horaSalida = vueloIda.getHora();
        this.categoria = categoria;
        this.isIdaVuelta = isIdaVuelta;    
        this.isEquipaje = isEquipaje;
        this.peso = peso;
        this.peso1 = peso1;
        initComponents();
        this.setTitle("Airline Tickets Application");
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono avion.png")).getImage());
        
        if(!isIdaVuelta)
            configuracionInicial();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombrePasajero = new java.awt.Label();
        docIdentidadT = new java.awt.Label();
        numeroReservaT = new java.awt.Label();
        nombreL = new javax.swing.JLabel();
        docIDL = new javax.swing.JLabel();
        nReservaL = new javax.swing.JLabel();
        confirmarB = new javax.swing.JButton();
        volverB = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        origenT = new java.awt.Label();
        destinoT = new java.awt.Label();
        fechaSalidaT = new java.awt.Label();
        horaSalidaT = new java.awt.Label();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        IDVueloT = new java.awt.Label();
        origenL = new javax.swing.JLabel();
        destinoL = new javax.swing.JLabel();
        fechaSalidaL = new javax.swing.JLabel();
        horaSalidaL = new javax.swing.JLabel();
        vueloL = new javax.swing.JLabel();
        equipajeL = new javax.swing.JLabel();
        pesoEquipajeL = new javax.swing.JLabel();
        categoriaT = new java.awt.Label();
        categoriaL = new javax.swing.JLabel();
        noPuestosT = new java.awt.Label();
        noPuestosL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        origenVueltaT = new java.awt.Label();
        destinoVueltaT = new java.awt.Label();
        fechaVueltaT = new java.awt.Label();
        horaVuelta = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        vueloVuelta = new java.awt.Label();
        origenVueltaL = new javax.swing.JLabel();
        destinoVueltaL = new javax.swing.JLabel();
        fechaVueltaL = new javax.swing.JLabel();
        horaVueltaL = new javax.swing.JLabel();
        vueloVueltaL = new javax.swing.JLabel();
        equipajeVueltaL = new javax.swing.JLabel();
        pesoEquipajeVueltaL = new javax.swing.JLabel();
        categoriaVueltaT = new java.awt.Label();
        categoriaVueltaL = new javax.swing.JLabel();
        noPuestosVueltaT = new java.awt.Label();
        noPuestosVueltaL = new javax.swing.JLabel();
        panelPrecio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        subTotalL = new javax.swing.JLabel();
        impuestosL = new javax.swing.JLabel();
        totalL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("RESERVA");

        nombrePasajero.setBackground(java.awt.Color.lightGray);
        nombrePasajero.setText("Nombre pasajero:");

        docIdentidadT.setBackground(java.awt.Color.lightGray);
        docIdentidadT.setText("Doc. de Identidad:");

        numeroReservaT.setBackground(java.awt.Color.lightGray);
        numeroReservaT.setText("Número de Reserva:");

        nombreL.setText("nombre");

        docIDL.setText("docID");

        nReservaL.setText("numero Reserva");

        confirmarB.setText("Confirmar");
        confirmarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBActionPerformed(evt);
            }
        });

        volverB.setText("Volver");
        volverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBActionPerformed(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        origenT.setAlignment(java.awt.Label.CENTER);
        origenT.setBackground(java.awt.Color.lightGray);
        origenT.setText("Origen");

        destinoT.setAlignment(java.awt.Label.CENTER);
        destinoT.setBackground(java.awt.Color.lightGray);
        destinoT.setText("Destino");

        fechaSalidaT.setAlignment(java.awt.Label.CENTER);
        fechaSalidaT.setBackground(java.awt.Color.lightGray);
        fechaSalidaT.setText("Fecha");

        horaSalidaT.setAlignment(java.awt.Label.CENTER);
        horaSalidaT.setBackground(java.awt.Color.lightGray);
        horaSalidaT.setText("Hora");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.lightGray);
        label1.setText("Equipaje");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(java.awt.Color.lightGray);
        label2.setText("Peso Equipaje");

        IDVueloT.setAlignment(java.awt.Label.CENTER);
        IDVueloT.setBackground(java.awt.Color.lightGray);
        IDVueloT.setText("Vuelo");

        origenL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        origenL.setText("Origen");

        destinoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destinoL.setText("Destino");

        fechaSalidaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaSalidaL.setText("Fecha");

        horaSalidaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horaSalidaL.setText("Hora");

        vueloL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vueloL.setText("Vuelo");

        equipajeL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipajeL.setText("Equipaje");

        pesoEquipajeL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoEquipajeL.setText("Peso equipaje");

        categoriaT.setAlignment(java.awt.Label.CENTER);
        categoriaT.setBackground(java.awt.Color.lightGray);
        categoriaT.setText("Categoría");

        categoriaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoriaL.setText("Categoría");

        noPuestosT.setAlignment(java.awt.Label.CENTER);
        noPuestosT.setBackground(java.awt.Color.lightGray);
        noPuestosT.setText("No. puestos");

        noPuestosL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noPuestosL.setText("No. Puestos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(origenT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinoT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(origenL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(destinoL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noPuestosT, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(noPuestosL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaSalidaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalidaT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(horaSalidaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaSalidaT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoriaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(equipajeL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesoEquipajeL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vueloL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDVueloT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDVueloT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaSalidaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalidaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noPuestosT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenL)
                    .addComponent(destinoL)
                    .addComponent(fechaSalidaL)
                    .addComponent(horaSalidaL)
                    .addComponent(vueloL)
                    .addComponent(equipajeL)
                    .addComponent(pesoEquipajeL)
                    .addComponent(categoriaL)
                    .addComponent(noPuestosL))
                .addContainerGap())
        );

        horaSalidaT.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Vuelo Ida", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        origenVueltaT.setAlignment(java.awt.Label.CENTER);
        origenVueltaT.setBackground(java.awt.Color.lightGray);
        origenVueltaT.setText("Origen");

        destinoVueltaT.setAlignment(java.awt.Label.CENTER);
        destinoVueltaT.setBackground(java.awt.Color.lightGray);
        destinoVueltaT.setText("Destino");

        fechaVueltaT.setAlignment(java.awt.Label.CENTER);
        fechaVueltaT.setBackground(java.awt.Color.lightGray);
        fechaVueltaT.setText("Fecha");

        horaVuelta.setAlignment(java.awt.Label.CENTER);
        horaVuelta.setBackground(java.awt.Color.lightGray);
        horaVuelta.setText("Hora");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(java.awt.Color.lightGray);
        label3.setText("Equipaje");

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(java.awt.Color.lightGray);
        label4.setText("Peso Equipaje");

        vueloVuelta.setAlignment(java.awt.Label.CENTER);
        vueloVuelta.setBackground(java.awt.Color.lightGray);
        vueloVuelta.setText("Vuelo");

        origenVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        origenVueltaL.setText("Ninguno");

        destinoVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destinoVueltaL.setText("Ninguno");

        fechaVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaVueltaL.setText("Ninguna");

        horaVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horaVueltaL.setText("Ninguna");

        vueloVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vueloVueltaL.setText("Ninguno");

        equipajeVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipajeVueltaL.setText("Ninguno");

        pesoEquipajeVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesoEquipajeVueltaL.setText("Ninguno");

        categoriaVueltaT.setAlignment(java.awt.Label.CENTER);
        categoriaVueltaT.setBackground(java.awt.Color.lightGray);
        categoriaVueltaT.setText("Categoría");

        categoriaVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoriaVueltaL.setText("Ninguna");

        noPuestosVueltaT.setAlignment(java.awt.Label.CENTER);
        noPuestosVueltaT.setBackground(java.awt.Color.lightGray);
        noPuestosVueltaT.setText("No. Puestos");

        noPuestosVueltaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noPuestosVueltaL.setText("Ninguno");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(origenVueltaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(origenVueltaT, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destinoVueltaT, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(destinoVueltaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noPuestosVueltaT, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(noPuestosVueltaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(fechaVueltaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horaVueltaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(categoriaVueltaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriaVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vueloVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(equipajeVueltaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesoEquipajeVueltaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vueloVueltaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(323, 323, 323))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(categoriaVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaVueltaL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vueloVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horaVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinoVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origenVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noPuestosVueltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origenVueltaL)
                            .addComponent(destinoVueltaL)
                            .addComponent(fechaVueltaL)
                            .addComponent(horaVueltaL)
                            .addComponent(vueloVueltaL)
                            .addComponent(equipajeVueltaL)
                            .addComponent(pesoEquipajeVueltaL)
                            .addComponent(noPuestosVueltaL))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vuelo Vuelta", jPanel3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Precio");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Sub total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Impuestos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total");

        javax.swing.GroupLayout panelPrecioLayout = new javax.swing.GroupLayout(panelPrecio);
        panelPrecio.setLayout(panelPrecioLayout);
        panelPrecioLayout.setHorizontalGroup(
            panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrecioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelPrecioLayout.createSequentialGroup()
                        .addGroup(panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subTotalL, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(impuestosL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelPrecioLayout.setVerticalGroup(
            panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrecioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subTotalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(impuestosL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrecioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(totalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numeroReservaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombrePasajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(docIdentidadT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docIDL)
                            .addComponent(nReservaL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docIdentidadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docIDL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroReservaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nReservaL))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarB)
                    .addComponent(volverB))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBActionPerformed
        // TODO add your handling code here:
        ReservaDAO rdao = new ReservaDAO();
        //sistema.addReservas(reserva);
        rdao.crear(reserva);
        System.out.println("-------");
        System.out.println("RESERVACIÓN REALIZADA");
        System.out.println();
        System.out.println("Nombre: " + reserva.getUsuario().getNombre());
        System.out.println("Apellido: " + reserva.getUsuario().getApellido());
        System.out.println("ID reserva: " + reserva.getId());
        System.out.println("Es ida y vuelta: " + reserva.isIdaVuelta());
        
        MenuInicial menu = new MenuInicial();
        this.setVisible(false);
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
    }//GEN-LAST:event_confirmarBActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if(isIdaVuelta) {
            origenVueltaL.setText(destino);
            destinoVueltaL.setText(origen);
            fechaVueltaL.setText(vueloVuelta1.getFecha());
            horaVueltaL.setText(vueloVuelta1.getHora());
            categoriaVueltaL.setText(categoriaVuelta);
            String resultado2;
            if(isEquipajeVuelta) resultado2 = "Sí";
            else resultado2 = "No";
            noPuestosVueltaL.setText(("" + puestosReservadosVuelta));
            equipajeVueltaL.setText(resultado2);
            pesoEquipajeVueltaL.setText(peso1Vuelta);
            vueloVueltaL.setText(("" + vueloVuelta1.getId()));
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void volverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        if(isIdaVuelta) {
            reservationVuelta reservacion = new reservationVuelta(isEquipaje, origen, destino, fechaSalida, horaSalida, categoria, peso1, puestosReservados, peso);
            reservacion.setLocationRelativeTo(this);
            reservacion.setVisible(true);
        }
        
        else {
            ReservationIda reservacion = new ReservationIda();
            reservacion.setLocationRelativeTo(this);
            reservacion.setVisible(true);
        }
    }//GEN-LAST:event_volverBActionPerformed
    
    private void configuracionInicial() {
        nombreL.setText(user.getNombre());
        nReservaL.setText(("" + numeroReserva));
        docIDL.setText("101010");
        origenL.setText(origen);
        destinoL.setText(destino);
        noPuestosL.setText(("" + puestosReservados));
        fechaSalidaL.setText(fechaSalida);
        horaSalidaL.setText(horaSalida);
        categoriaL.setText(categoria);
        String resultado1;
        if(isEquipaje) resultado1 = "Sí";
        else resultado1 = "No";
        equipajeL.setText(resultado1);
        pesoEquipajeL.setText(peso1);
        vueloL.setText(("" + vueloIda.getId()));
        
        CalcularPrecio calcular = new CalcularPrecio();
        
        reserva = new Reserva(vueloIda, puestosReservados, isIdaVuelta, isEquipaje, peso, categoria, user);
        reserva.setPeso(peso);
        
        if(isIdaVuelta) {
            reserva.setVueloVuelta(vueloVuelta1);
            reserva.setEquipajeVuelta(isEquipajeVuelta);
            reserva.setCategoriaVuelta(categoriaVuelta);
            reserva.setPesoVuelta(pesoVuelta);
            reserva.setNumeroPuestosvuelta(puestosReservadosVuelta);
        }
        
        precioSubtotal = (calcular.calcularPrecio(reserva) * (puestosReservados + puestosReservadosVuelta));
        precioImpuestos = (calcular.calcularIva(reserva) * (puestosReservados + puestosReservadosVuelta));
        precioTotal = (calcular.precioFinal(reserva) * (puestosReservados + puestosReservadosVuelta));
        
        subTotalL.setText(("" + precioSubtotal + " USD"));
        impuestosL.setText(("" + precioImpuestos + " USD"));
        totalL.setText(("" + precioTotal + " USD"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label IDVueloT;
    private javax.swing.JLabel categoriaL;
    private java.awt.Label categoriaT;
    private javax.swing.JLabel categoriaVueltaL;
    private java.awt.Label categoriaVueltaT;
    private javax.swing.JButton confirmarB;
    private javax.swing.JLabel destinoL;
    private java.awt.Label destinoT;
    private javax.swing.JLabel destinoVueltaL;
    private java.awt.Label destinoVueltaT;
    private javax.swing.JLabel docIDL;
    private java.awt.Label docIdentidadT;
    private javax.swing.JLabel equipajeL;
    private javax.swing.JLabel equipajeVueltaL;
    private javax.swing.JLabel fechaSalidaL;
    private java.awt.Label fechaSalidaT;
    private javax.swing.JLabel fechaVueltaL;
    private java.awt.Label fechaVueltaT;
    private javax.swing.JLabel horaSalidaL;
    private java.awt.Label horaSalidaT;
    private java.awt.Label horaVuelta;
    private javax.swing.JLabel horaVueltaL;
    private javax.swing.JLabel impuestosL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel nReservaL;
    private javax.swing.JLabel noPuestosL;
    private java.awt.Label noPuestosT;
    private javax.swing.JLabel noPuestosVueltaL;
    private java.awt.Label noPuestosVueltaT;
    private javax.swing.JLabel nombreL;
    private java.awt.Label nombrePasajero;
    private java.awt.Label numeroReservaT;
    private javax.swing.JLabel origenL;
    private java.awt.Label origenT;
    private javax.swing.JLabel origenVueltaL;
    private java.awt.Label origenVueltaT;
    private javax.swing.JPanel panelPrecio;
    private javax.swing.JLabel pesoEquipajeL;
    private javax.swing.JLabel pesoEquipajeVueltaL;
    private javax.swing.JLabel subTotalL;
    private javax.swing.JLabel totalL;
    private javax.swing.JButton volverB;
    private javax.swing.JLabel vueloL;
    private java.awt.Label vueloVuelta;
    private javax.swing.JLabel vueloVueltaL;
    // End of variables declaration//GEN-END:variables

    public String getCategoriaVuelta() {
        return categoriaVuelta;
    }

    public void setCategoriaVuelta(String categoriaVuelta) {
        this.categoriaVuelta = categoriaVuelta;
    }

    public boolean isIsEquipajeVuelta() {
        return isEquipajeVuelta;
    }

    public void setIsEquipajeVuelta(boolean isEquipajeVuelta) {
        this.isEquipajeVuelta = isEquipajeVuelta;
    }

    public int getPuestosReservadosVuelta() {
        return puestosReservadosVuelta;
    }

    public void setPuestosReservadosVuelta(int puestosReservadosVuelta) {
        this.puestosReservadosVuelta = puestosReservadosVuelta;
    }

    public int getPesoVuelta() {
        return pesoVuelta;
    }

    public void setPesoVuelta(int pesoVuelta) {
        this.pesoVuelta = pesoVuelta;
        configuracionInicial();
    }

    public String getPeso1Vuelta() {
        return peso1Vuelta;
    }

    public void setPeso1vuelta(String peso1Vuelta) {
        this.peso1Vuelta = peso1Vuelta;
    }
    
    public Vuelo getVueloVuelta1() {
        return vueloVuelta1;
    }

    public void setVueloVuelta1(Vuelo vueloVuelta1) {
        this.vueloVuelta1 = vueloVuelta1;
        
    }
}
