/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarPagoTarjeta;
import DAO.CreditCardDAO;
import DAO.ReservaDAO;
import DAO.TicketDAO;
import Entidad.CreditCard;
import Entidad.Reserva;
import Entidad.Ticket;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author nicro
 */
public class ReservationPayment extends javax.swing.JFrame {
    boolean reservaActived;
    Reserva reserva;
    ReservaDAO rdao;
    List<Reserva> listReserva;
    
    /**
     * Creates new form TicketPayment
     */
    public ReservationPayment() {
        initComponents();
        this.setTitle("Airline Tickets Application");
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono avion.png")).getImage());
        
        reserva = null;
        rdao = new ReservaDAO();
        listReserva = rdao.leeralltolist();
        reservaActived = false;
        informacionTarjetaL.setVisible(false);
        nombreBancoL.setVisible(false);
        nombreBancoTF.setVisible(false);
        fechaCaducidadL.setVisible(false);
        fechaCaducidadTF.setVisible(false);
        nombreTitularL.setVisible(false);
        nombreTitularTF.setVisible(false);
        marcaInternacionalL.setVisible(false);
        marcaInternacionalTF.setVisible(false);
        numeroTarjetaL.setVisible(false);
        numeroTarjetaTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idReservacionL = new javax.swing.JLabel();
        idReservacionTF = new javax.swing.JTextField();
        avisoL = new javax.swing.JLabel();
        informacionTarjetaL = new javax.swing.JLabel();
        nombreBancoL = new javax.swing.JLabel();
        fechaCaducidadL = new javax.swing.JLabel();
        nombreTitularL = new javax.swing.JLabel();
        marcaInternacionalL = new javax.swing.JLabel();
        numeroTarjetaL = new javax.swing.JLabel();
        nombreBancoTF = new javax.swing.JTextField();
        fechaCaducidadTF = new javax.swing.JTextField();
        nombreTitularTF = new javax.swing.JTextField();
        marcaInternacionalTF = new javax.swing.JTextField();
        numeroTarjetaTF = new javax.swing.JTextField();
        aceptarConfirmarB = new javax.swing.JButton();
        volverCambiarDeReservaB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pago de Reservación");

        idReservacionL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idReservacionL.setText("ID reservación");

        idReservacionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservacionTFActionPerformed(evt);
            }
        });
        idReservacionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idReservacionTFKeyTyped(evt);
            }
        });

        avisoL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        avisoL.setForeground(java.awt.Color.red);

        informacionTarjetaL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        informacionTarjetaL.setText("Informacion Tarjeta de Crédito");

        nombreBancoL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBancoL.setText("Nombre del banco");

        fechaCaducidadL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaCaducidadL.setText("Fecha de caducidad");

        nombreTitularL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreTitularL.setText("Nombre del titular");

        marcaInternacionalL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marcaInternacionalL.setText("Marca internacional");

        numeroTarjetaL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroTarjetaL.setText("Numero de la tarjeta");

        nombreBancoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreBancoTFActionPerformed(evt);
            }
        });

        aceptarConfirmarB.setText("Aceptar");
        aceptarConfirmarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarConfirmarBActionPerformed(evt);
            }
        });

        volverCambiarDeReservaB.setText("Volver");
        volverCambiarDeReservaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverCambiarDeReservaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(informacionTarjetaL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(volverCambiarDeReservaB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aceptarConfirmarB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(avisoL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroTarjetaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(marcaInternacionalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreBancoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreTitularL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaCaducidadL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(marcaInternacionalTF)
                                    .addComponent(nombreTitularTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaCaducidadTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombreBancoTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numeroTarjetaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idReservacionL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(idReservacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idReservacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idReservacionL))
                .addGap(28, 28, 28)
                .addComponent(informacionTarjetaL)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nombreBancoL)
                                            .addComponent(nombreBancoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(fechaCaducidadL))
                                    .addComponent(fechaCaducidadTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(nombreTitularL))
                            .addComponent(nombreTitularTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(marcaInternacionalL))
                    .addComponent(marcaInternacionalTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numeroTarjetaL)
                    .addComponent(numeroTarjetaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(avisoL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarConfirmarB)
                    .addComponent(volverCambiarDeReservaB))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idReservacionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservacionTFActionPerformed
        // TODO add your handling code here:
        ValidarPagoTarjeta validar = new ValidarPagoTarjeta();
        
        String id = idReservacionTF.getText();
        
        if(id.length() != 0) {
            if(validar.verificarReserva(Integer.parseInt(id))) {
                informacionTarjetaL.setVisible(true);
                nombreBancoL.setVisible(true);
                nombreBancoTF.setVisible(true);
                fechaCaducidadL.setVisible(true);
                fechaCaducidadTF.setVisible(true);
                nombreTitularL.setVisible(true);
                nombreTitularTF.setVisible(true);
                marcaInternacionalL.setVisible(true);
                marcaInternacionalTF.setVisible(true);
                numeroTarjetaL.setVisible(true);
                numeroTarjetaTF.setVisible(true);
                avisoL.setText("");
                idReservacionTF.setEnabled(false);
                aceptarConfirmarB.setText("Confirmar");
                volverCambiarDeReservaB.setText("Cambiar reserva");
                reservaActived = true;
                
                for(int i = 0; i < listReserva.size(); i++) {
                    if(listReserva.get(i).getId() == Integer.parseInt(id))
                        reserva = listReserva.get(i);
                }
            }
        
            else {
                avisoL.setText("La reserva no existe");
            }
        }
        
        else {
            avisoL.setText("Ingrese una reservación");
        }
    }//GEN-LAST:event_idReservacionTFActionPerformed

    private void nombreBancoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreBancoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreBancoTFActionPerformed

    private void aceptarConfirmarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarConfirmarBActionPerformed
        // TODO add your handling code here:
        ValidarPagoTarjeta validar = new ValidarPagoTarjeta();
        String id = idReservacionTF.getText();
        
        if(!reservaActived) {
            if(id.length() != 0) {
                if(validar.verificarReserva(Integer.parseInt(id))) {
                    informacionTarjetaL.setVisible(true);
                    nombreBancoL.setVisible(true);
                    nombreBancoTF.setVisible(true);
                    fechaCaducidadL.setVisible(true);
                    fechaCaducidadTF.setVisible(true);
                    nombreTitularL.setVisible(true);
                    nombreTitularTF.setVisible(true);
                    marcaInternacionalL.setVisible(true);
                    marcaInternacionalTF.setVisible(true);
                    numeroTarjetaL.setVisible(true);
                    numeroTarjetaTF.setVisible(true);
                    avisoL.setText("");
                    idReservacionTF.setEnabled(false);
                    aceptarConfirmarB.setText("Confirmar");
                    volverCambiarDeReservaB.setText("Cambiar reserva");
                    reservaActived = true;
                
                    for(int i = 0; i < listReserva.size(); i++) {
                        if(listReserva.get(i).getId() == Integer.parseInt(id))
                            reserva = listReserva.get(i);
                    }    
                }
        
                else {
                avisoL.setText("La reserva no existe");
                }
            }
        
            else {
                avisoL.setText("Ingrese una reservación");
            }
        }
        
        else {
            String nombreBanco = nombreBancoTF.getText(), fechaCaducidad = fechaCaducidadTF.getText(), nombreTitular = nombreTitularTF.getText(), 
                    marcaInternacional = marcaInternacionalTF.getText(), numeroTarjeta = numeroTarjetaTF.getText();
            
            CreditCard tarjetaIngresada = new CreditCard(nombreBanco, fechaCaducidad, nombreTitular, marcaInternacional, numeroTarjeta);
            
            CreditCardDAO tdao = new CreditCardDAO();
            List<CreditCard> lista = tdao.leeralltolist();
            CreditCard tarjetaAntigua = null;
                
            for(int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getNombreBanco().equals(nombreBanco) && lista.get(i).getFechaCaducidad().equals(fechaCaducidad) && lista.get(i).getMarcaInternacional().equals(marcaInternacional)
                        && lista.get(i).getNombreTitular().equals(nombreTitular) && lista.get(i).getNumeroTarjeta().equals(numeroTarjeta)) {
                        
                    tarjetaAntigua = lista.get(i);
                }
            }
                
            String resultado = null;
                
            if(tarjetaAntigua.equals(null)) {
                resultado = validar.verificarPagoTarjeta(Integer.parseInt(id), tarjetaIngresada, reserva.getPrecio());
            }
                
            else {
                resultado = validar.verificarPagoTarjeta(Integer.parseInt(id), tarjetaAntigua, reserva.getPrecio());
            }
            
            if(resultado.equals("Longitud del nombre del banco incorrecta")) 
                avisoL.setText("Longitud del nombre del banco incorrecta");
            
            else if(resultado.equals("Formato de fecha incorrecta")) 
                avisoL.setText("Formato de fecha incorrecta");
            
            else if(resultado.equals("Longitud del nombre del titular incorrecta")) 
                avisoL.setText("Longitud del nombre del titular incorrecta");
            
            else if(resultado.equals("Longitud de marca internacional incorrecta")) 
                avisoL.setText("Longitud de marca internacional incorrecta");
            
            else if(resultado.equals("Longitud del numero de la tarjeta incorrecta")) 
                avisoL.setText("Longitud del numero de la tarjeta incorrecta");
            
            else if(resultado.equals("La tarjeta de crédito no se encuentra registrada"))
                avisoL.setText("La tarjeta de crédito no se encuentra registrada");
            
            else if(resultado.equals("No hay cupo necesario en la tarjeta para realizar el pago")) 
                avisoL.setText("No hay cupo necesario en la tarjeta para realizar el pago");
                
            else {
                CreditCard tarjetaNueva = tarjetaAntigua;
                double cupoGastado = tarjetaAntigua.getCupoGastado();
                tarjetaNueva.setCupoGastado(cupoGastado + reserva.getPrecio());
                
                tdao.actualizarId(tarjetaAntigua, tarjetaNueva);
                
                TicketDAO tckdao = new TicketDAO();
                Ticket ticketPagado = new Ticket(reserva);
                
                tckdao.crear(ticketPagado);
                
                this.setVisible(false);
                MenuInicial menu = new MenuInicial();
                menu.setVisible(true);
                menu.setLocationRelativeTo(this);
                menu.setVisible(true);
                menu.setAlwaysOnTop(true);
            }
            
            System.out.println("-------");
            System.out.println(resultado);
        }
    }//GEN-LAST:event_aceptarConfirmarBActionPerformed

    private void volverCambiarDeReservaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverCambiarDeReservaBActionPerformed
        // TODO add your handling code here:
        if(reservaActived) {
            reservaActived = false;
            informacionTarjetaL.setVisible(false);
            nombreBancoL.setVisible(false);
            nombreBancoTF.setVisible(false);
            fechaCaducidadL.setVisible(false);
            fechaCaducidadTF.setVisible(false);
            nombreTitularL.setVisible(false);
            nombreTitularTF.setVisible(false);
            marcaInternacionalL.setVisible(false);
            marcaInternacionalTF.setVisible(false);
            numeroTarjetaL.setVisible(false);
            numeroTarjetaTF.setVisible(false);
            avisoL.setText("");
            volverCambiarDeReservaB.setText("Volver");
            aceptarConfirmarB.setText("Aceptar");
            reservaActived = false;
            idReservacionTF.setEnabled(true);
        }
        
        else {
            this.setVisible(reservaActived);
            MenuInicial menu = new MenuInicial();
            menu.setVisible(true);
            menu.setLocationRelativeTo(this);
            menu.setVisible(true);
            menu.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_volverCambiarDeReservaBActionPerformed

    private void idReservacionTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idReservacionTFKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c < '0' || c > '9') //Sólo se puede escribir números
            evt.consume();
    }//GEN-LAST:event_idReservacionTFKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarConfirmarB;
    private javax.swing.JLabel avisoL;
    private javax.swing.JLabel fechaCaducidadL;
    private javax.swing.JTextField fechaCaducidadTF;
    private javax.swing.JLabel idReservacionL;
    private javax.swing.JTextField idReservacionTF;
    private javax.swing.JLabel informacionTarjetaL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcaInternacionalL;
    private javax.swing.JTextField marcaInternacionalTF;
    private javax.swing.JLabel nombreBancoL;
    private javax.swing.JTextField nombreBancoTF;
    private javax.swing.JLabel nombreTitularL;
    private javax.swing.JTextField nombreTitularTF;
    private javax.swing.JLabel numeroTarjetaL;
    private javax.swing.JTextField numeroTarjetaTF;
    private javax.swing.JButton volverCambiarDeReservaB;
    // End of variables declaration//GEN-END:variables
}
