/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import javax.swing.ImageIcon;
import Control.CalcularEstadisticas;
import Entidad.Vuelo;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Nicolás
 */
public class Statistics extends javax.swing.JFrame {

    CalcularEstadisticas est = new CalcularEstadisticas();
    List<Vuelo> vuelosVendidos;
    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        this.setTitle("Airline Tickets Application");
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono avion.png")).getImage());
        this.setSize(500, 280);
        getEstadisticas();
    }
    
    private void getEstadisticas(){
        vuelosVendidos = est.trayectoMasVendido();
        Vuelo v = est.calcularMayor(vuelosVendidos);
        trayecto.setText(v.getOrigen()+"-"+v.getDestino() + " (" + v.getSillasTotales() + " puestos)");
        mes.setText(est.fechaMasVendida());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        trayecto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 215));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 215));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Estadísticas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Trayecto más vendido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        trayecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        trayecto.setText("trayecto");
        jPanel1.add(trayecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mes con mayor número de ventas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        mes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mes.setText("mes");
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jButton2.setText("Crear gráfica trayectos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuInicial menu = new MenuInicial();
            menu.setLocationRelativeTo(this);
            this.setVisible(false);
            menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(vuelosVendidos.size() == 0) {
            generarEstadisticas();
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void generarEstadisticas() {
        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            
            if(vuelosVendidos.size() <= 5) {
                for(Vuelo v : vuelosVendidos) {
                    ds.addValue(v.getSillasTotales(), v.getOrigen() + " - " + v.getDestino(), "");
                }
            } else {
                for (int i = 0; i < 5; i++) {
                    Vuelo v = vuelosVendidos.get(i);
                    ds.addValue(v.getSillasTotales(), v.getOrigen() + " - " + v.getDestino(), "");
                }
            }
            
            JFreeChart jf = ChartFactory.createBarChart3D("Vuelos más vendidos", "Vuelos", "Cantidad de ventas", ds, PlotOrientation.VERTICAL, true, true, true);
            
            ChartFrame cf = new ChartFrame("Estadísticas vuelos más vendidos", jf);
            cf.setSize(700, 800);
            cf.setLocationRelativeTo(null);
            cf.setVisible(true);
            
        } catch(Exception e) {
            System.out.println("Error" + e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mes;
    private javax.swing.JLabel trayecto;
    // End of variables declaration//GEN-END:variables
}
